services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - db
    environment:
      - KAFKA_BROKER=kafka:9092
      - DATABASE_URL=postgresql://user:password@db:5432/orders_db

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    depends_on:
      - fastapi
      - kafka
      - db
    environment:
      - KAFKA_BROKER=kafka:9092
      - DATABASE_URL=postgresql://user:password@db:5432/orders_db
      - CELERY_BROKER_URL=kafka://kafka:9092
      - CELERY_RESULT_BACKEND=rpc://

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/orders_db
    command: ["sh", "-c", "./run_tests.sh"]

volumes:
  postgres_data: